concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: 16.x


      - run: pnpm install --frozen-lockfile
      - env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        id: changesets
        name: Create Release Pull Request or Publish
        uses: changesets/action@v1        
        with:
          publish: pnpm run release
          


name: Publish
on:
  push:
    branches:
      - "main"
  workflow_run:
    types:
      - completed
    workflows: ["CI"]

